#!/usr/bin/python
# -*- coding: utf-8 -*-
# ==============================================================================
#  XVATOOL PLUGIN - Forensic DFIR Audit & Chain of Custody Report Engine
# ==============================================================================
#  Copyright (c) 2026 Alexander Maassen <outsider@cuci.nl>
#  Licensed under the terms of the MIT License (See LICENSE.md in root)
# ==============================================================================
"""
Dynamic DFIR audit report extension module.
Compiles structurally verifiable cryptographic and environment metadata logs.
"""

import os
import sys
import time
import platform
import getpass

def is_supported():
	"""Proactive Environment Check. Always returns True as it relies on core Python."""
	return True


def register_arguments(parser):
	"""Attaches forensic administrative tracking variables to the core parser layer."""
	group = parser.add_argument_group("Forensic Audit Reporting Options")
	group.add_argument("--case-number", default="CASE-UNDEFINED",
		help="Specify the unique case file number string for the investigator dossier")
	group.add_argument("--evidence-id", default="EVID-UNDEFINED",
		help="Specify the target evidence item reference key identifier token")
	group.add_argument("--notes", default="Automated extraction pipeline run",
		help="Custom text string details to embed into the metadata header file")


def compile_report(target_image_path, checksum_dict, args=None):
	"""
	Generates an unassailable, structured flat-file forensic audit log sheet 
	directly alongside the extracted volume output path to preserve the chain of custody.
	"""
	report_file_path = target_image_path + ".report"
	timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
	
	case_num = "CASE-UNDEFINED"
	evid_id = "EVID-UNDEFINED"
	notes_str = "Automated extraction pipeline run"
	
	if args:
		if hasattr(args, 'case_number'): case_num = args.case_number
		if hasattr(args, 'evidence_id'): evid_id = args.evidence_id
		if hasattr(args, 'notes'): notes_str = args.notes

	try:
		with open(report_file_path, "w") as rf:
			rf.write("==============================================================================\n")
			rf.write("           XVATOOL ENTERPRISE DIGITAL FORENSICS AUDIT REPORT ENGINE\n")
			rf.write("==============================================================================\n")
			rf.write(" Generated By:       Alexander Maassen <outsider@cuci.nl>\n")
			rf.write(" Framework Version:  1.0.0\n")
			rf.write(" Verification Date:  {}\n".format(timestamp))
			rf.write("==============================================================================\n\n")
			
			rf.write("[INVESTIGATION METADATA]\n")
			rf.write("Case Number:        {}\n".format(case_num))
			rf.write("Evidence ID:        {}\n".format(evid_id))
			rf.write("Operator ID:        {} (UID={})\n".format(getpass.getuser(), os.getuid() if hasattr(os, 'getuid') else 0))
			rf.write("Notes / Description:{}\n\n".format(notes_str))
			
			rf.write("[SYSTEM ENVIRONMENT BLOCK]\n")
			rf.write("Host Node Name:     {}\n".format(platform.node()))
			rf.write("Operating System:   {}\n".format(platform.platform()))
			rf.write("Active Kernel Build:{}\n".format(platform.uname()[2]))
			rf.write("Process ID (PID):   {}\n\n".format(os.getpid()))
			
			rf.write("[RESOURCE ACQUISITION TARGETS]\n")
			rf.write("Destination Image:  {}\n".format(os.path.basename(target_image_path)))
			rf.write("FHS Physical Path:  {}\n".format(os.path.abspath(target_image_path)))
			if os.path.exists(target_image_path):
				rf.write("Volume Size Bounds: {} bytes ({})\n\n".format(
					os.path.getsize(target_image_path),
					format_size(os.path.getsize(target_image_path)) if 'format_size' in globals() else "Unmeasured"
				))
			else:
				rf.write("Volume Size Bounds: Stream interrupted or target unallocated.\n\n")

			rf.write("[CRYPTOGRAPHIC INTEGRITY CHECK]\n")
			# Enforce absolute validation fingerprints logging mappings
			rf.write("MD5 Hashing Block:  {}\n".format(checksum_dict.get("md5", "NOT_COMPUTED").upper()))
			rf.write("SHA-1 Hashing Block:{}\n".format(checksum_dict.get("sha1", "NOT_COMPUTED").upper()))
			rf.write("SHA-256 Hash Grid:  {}\n".format(checksum_dict.get("sha256", "NOT_COMPUTED").upper()))
			rf.write("==============================================================================\n")
			rf.write("       CHAIN OF CUSTODY VERIFIED - DATA ACQUISITION LOG TRANSCRIPTION EOF\n")
			rf.write("==============================================================================\n")
			
		return True
	except (IOError, OSError) as e:
		sys.stderr.write("[!] Forensic Reporting Engine Failure: " + str(e) + "\n")
		return False
